#!/bin/bash

#Download pathogen
mkdir -p ~/.vim ~/.vim/autoload ~/.vim/bundle && \
	curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

#Install Vim Sensible -- set of default settings
git clone git://github.com/tpope/vim-sensible.git ~/.vim/bundle/vim-sensible

#Install Auto Pairs (Bracket Matching)
git clone git://github.com/jiangmiao/auto-pairs.git ~/.vim/bundle/auto-pairs

#Install Vim Colors
git clone git://github.com/altercation/vim-colors-solarized.git ~/.vim/bundle/vim-colors-solarized

#Install ColorScheme
git clone https://github.com/wellsjo/wells-colorscheme.vim.git ~/.vim/bundle/wells-colorscheme.vim

#Install NERDTree
git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree

#Now write the .vimrc
cd ~ && curl -O https://muzfuz.github.io/stuff/vimrc
mv ~/vimrc ~/.vimrc

#Remove this file (cleanup)
rm ~/vimconfig
